#!/usr/bin/env bash
# ABOUTME: VI-5 morning brief — daily digest of overnight runs, queue state, staged items.
# ABOUTME: Checks kill-switch first; leads with FROZEN banner if tripped. Assembles brief
# ABOUTME: from: run manifests (state/runs/), staged patches (harness brief), queue depth
# ABOUTME: (harness queue ls), and harness recall context (timeout-guarded, fail-open).
# ABOUTME: Delivers via scripts/notify.sh; writes to docs/temp/briefings/YYYY-MM-DD.md.

set -uo pipefail

# ── Path resolution (env-overridable for tests) ───────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_HOME:-$HOME/.claude}"
STATE_ROOT="${MORNING_BRIEF_STATE_ROOT:-$CLAUDE_HOME/state}"
QUEUE_DIR="${MORNING_BRIEF_QUEUE_DIR:-$CLAUDE_HOME/queue}"
RUNS_DIR="${MORNING_BRIEF_RUNS_DIR:-$STATE_ROOT/runs}"
BRIEFINGS_DIR="${MORNING_BRIEF_OUTPUT_DIR:-$CLAUDE_HOME/docs/temp/briefings}"
HARNESS="${MORNING_BRIEF_HARNESS:-$CLAUDE_HOME/bin/harness}"
NOTIFY="${MORNING_BRIEF_NOTIFY:-$SCRIPT_DIR/notify.sh}"
NOTIFY_SKIP="${MORNING_BRIEF_NOTIFY_SKIP:-0}"
KS_SENTINEL="${STATE_ROOT}/.AUTONOMOUS_FREEZE"

# Stamp last-run for harness doctor stale-detection
_stamp_last_run() {
  printf '%s\n' "$(date +%s)" > "${STATE_ROOT}/com.yklin.morning-brief.last-run" 2>/dev/null || true
}
trap '_stamp_last_run' EXIT

mkdir -p "$BRIEFINGS_DIR" 2>/dev/null || true

TODAY="$(date +%Y-%m-%d)"
BRIEF_FILE="$BRIEFINGS_DIR/${TODAY}.md"

# Redirect all output to both file and stdout
exec > >(tee "$BRIEF_FILE") 2>&1

# ── Helpers ───────────────────────────────────────────────────────────────────

_section() { printf '\n## %s\n' "$1"; }

_harness() {
  # Run harness with state override; fail-open (never crashes brief)
  HARNESS_STATE_OVERRIDE="$STATE_ROOT" \
  STATE="$STATE_ROOT" \
  QUEUE_DIR="$QUEUE_DIR" \
    "$HARNESS" "$@" 2>/dev/null || true
}

_recall_context() {
  # Timeout-guarded recall; completely fail-open
  local query="$1"
  local result
  result="$(timeout 10 bash -c "HARNESS_STATE_OVERRIDE='$STATE_ROOT' '$HARNESS' recall '$query' 3 2>/dev/null" 2>/dev/null)" || true
  # If recall returned "not yet implemented" stub, suppress it
  if echo "$result" | grep -q "not yet implemented"; then
    return 0
  fi
  echo "$result"
}

_queue_counts() {
  # Count queue tasks by status; fail-open
  local enqueued started staged total=0
  enqueued=0; started=0; staged=0
  if [[ -d "$QUEUE_DIR" ]]; then
    while IFS= read -r f; do
      [[ -f "$f" ]] || continue
      local s
      s="$(grep -E '^status:' "$f" 2>/dev/null | head -1 | sed 's/status:[[:space:]]*//' | tr -d '[:space:]')"
      case "$s" in
        enqueued) (( enqueued++ )) || true ;;
        started)  (( started++  )) || true ;;
        staged)   (( staged++   )) || true ;;
      esac
      (( total++ )) || true
    done < <(find "$QUEUE_DIR" -name 'q-*.md' 2>/dev/null | sort)
  fi
  printf 'enqueued=%d started=%d staged=%d total=%d' "$enqueued" "$started" "$staged" "$total"
}

# ── Header ────────────────────────────────────────────────────────────────────
printf '# Morning Brief — %s\n' "$(date -u '+%Y-%m-%d %H:%M UTC')"
printf 'Generated by scripts/morning-brief.sh (VI-5)\n'

# ── Kill-switch check (FROZEN banner — MUST come first) ───────────────────────
FROZEN=0
if [[ -f "$KS_SENTINEL" ]]; then
  FROZEN=1
  FREEZE_CONTENT="$(cat "$KS_SENTINEL" 2>/dev/null || echo "unknown reason")"
  printf '\n'
  printf '╔═══════════════════════════════════════════════════════════════╗\n'
  printf '║  *** FROZEN — AUTONOMOUS EXECUTION HALTED ***                 ║\n'
  printf '╚═══════════════════════════════════════════════════════════════╝\n'
  printf '\nFreeze content: %s\n' "$FREEZE_CONTENT"
  printf '\nHow to clear: harness queue clear-freeze\n'
  printf '  (Interactive only — autonomous runs cannot self-unfreeze)\n'
fi

# ── Section: Overnight runs ───────────────────────────────────────────────────
_section "Overnight Runs (last 24h)"

run_count=0
empty_night=1
if [[ -d "$RUNS_DIR" ]]; then
  # Find manifests modified in the last 24h
  while IFS= read -r manifest; do
    [[ -f "$manifest" ]] || continue
    empty_night=0
    (( run_count++ )) || true
    local_id="$(python3 -c "import json,sys; d=json.load(open('$manifest')); print(d.get('task_id','unknown'))" 2>/dev/null || basename "$manifest" .json)"
    local_intent="$(python3 -c "import json,sys; d=json.load(open('$manifest')); print(d.get('intent',''))" 2>/dev/null || echo "")"

    # Re-derive status from evidence: manifest self-report is NEVER trusted.
    # Rule: a run is "done" only if every acceptance entry has exit_code==0.
    # If the manifest claims done but evidence disagrees → SUSPECT (anti-self-report, MASTER-03).
    # Fail-open: a malformed/missing manifest surfaces as "needs-review", never crashes.
    local_derived_status="$(python3 - "$manifest" 2>/dev/null <<'PYEOF'
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    manifest_status = d.get('status', 'unknown')
    criteria = d.get('acceptance', [])
    if not isinstance(criteria, list):
        # Malformed acceptance field — surface as needs-review
        print('needs-review (malformed acceptance field)')
        sys.exit(0)
    failed = [c for c in criteria if isinstance(c, dict) and c.get('exit_code', 0) != 0]
    if failed and manifest_status in ('done', 'staged', 'completed'):
        # Manifest claims success but acceptance evidence contradicts it — MISMATCH
        failing_criteria = '; '.join(c.get('criterion', str(c)) for c in failed)
        print(f'SUSPECT — manifest claimed "{manifest_status}" but acceptance FAILED: {failing_criteria}')
    elif failed:
        # Manifest already says non-success; acceptance confirms failure
        print(f'{manifest_status} [acceptance failed: {len(failed)} criterion(ia)]')
    else:
        # All acceptance entries are exit_code==0 (or no entries); trust the manifest status
        print(manifest_status)
except (json.JSONDecodeError, OSError, ValueError) as e:
    # Malformed manifest — surface as needs-review, never crash or default to "done"
    print(f'needs-review (manifest parse error: {e})')
PYEOF
    )" || local_derived_status="needs-review (status read failed)"

    printf '\n### %s\n' "$local_id"
    # Print re-derived status; print MISMATCH warning if status was laundered
    if echo "$local_derived_status" | grep -q "^SUSPECT"; then
      printf 'Status : %s\n' "$local_derived_status"
      printf '⚠ MISMATCH: manifest self-report contradicted by acceptance evidence — treat as FAILED\n'
    else
      printf 'Status : %s\n' "$local_derived_status"
    fi
    [[ -n "$local_intent" ]] && printf 'Intent : %s\n' "$local_intent"

    # Print acceptance results if present
    python3 - "$manifest" 2>/dev/null <<'PYEOF' || true
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    criteria = d.get('acceptance', [])
    if criteria:
        print('Acceptance:')
        for c in criteria:
            if isinstance(c, dict):
                ec = c.get('exit_code', '?')
                crit = c.get('criterion', str(c))
                mark = '[✓]' if ec == 0 else '[✗]'
                print(f'  {mark} {crit}')
            else:
                print(f'  - {c}')
except Exception as e:
    pass
PYEOF

    # Staged items get approve/reject actions (use raw manifest status for action routing,
    # not the derived status — a SUSPECT run should NOT be auto-approvable)
    local_raw_status="$(python3 -c "import json,sys; d=json.load(open('$manifest')); print(d.get('status','unknown'))" 2>/dev/null || echo "unknown")"
    if [[ "$local_raw_status" == "staged" ]] && ! echo "$local_derived_status" | grep -q "^SUSPECT"; then
      printf '\nActions:\n'
      printf '  harness queue approve %s\n' "$local_id"
      printf '  harness queue reject  %s\n' "$local_id"
    fi
  done < <(find "$RUNS_DIR" -name '*.json' -newer "${RUNS_DIR}/.oldest-marker" 2>/dev/null \
           || find "$RUNS_DIR" -name '*.json' 2>/dev/null | sort -r | head -20)
fi

if [[ "$empty_night" -eq 1 ]]; then
  printf '\n_(empty night — no runs found in %s)_\n' "$RUNS_DIR"
  printf '\nNothing ran overnight. Queue is quiet.\n'
fi

# ── Section: Staged patches from harness brief ────────────────────────────────
_section "Staged Patches (flywheel)"
# Capture harness brief STAGED PATCHES section only
staged_patches="$(_harness brief 2>/dev/null | awk '/STAGED PATCHES/,/═══/' | grep -v '═══' || echo "")"
if [[ -n "$staged_patches" ]] && ! echo "$staged_patches" | grep -q "no staged patches"; then
  printf '%s\n' "$staged_patches"
else
  printf '_(no flywheel staged patches pending)_\n'
fi

# ── Section: Queue depth ──────────────────────────────────────────────────────
_section "Queue Depth"
counts="$(_queue_counts)"
enqueued_n="$(echo "$counts" | grep -oE 'enqueued=[0-9]+' | cut -d= -f2)"
started_n="$(echo "$counts" | grep -oE 'started=[0-9]+'  | cut -d= -f2)"
staged_n="$(echo "$counts"  | grep -oE 'staged=[0-9]+'   | cut -d= -f2)"
total_n="$(echo "$counts"   | grep -oE 'total=[0-9]+'    | cut -d= -f2)"

printf 'enqueued: %s  |  started: %s  |  staged: %s  |  total: %s\n' \
  "${enqueued_n:-0}" "${started_n:-0}" "${staged_n:-0}" "${total_n:-0}"

if [[ "${total_n:-0}" -gt 0 ]]; then
  printf '\nQueue listing:\n'
  _harness queue ls 2>/dev/null | head -40 || printf '  (queue ls unavailable)\n'
else
  printf '\n_(queue is empty)_\n'
fi

# ── Section: Recall context (Pillar V, timeout-guarded) ───────────────────────
# Only show if there's a high-priority enqueued task to provide context for
_section "Recall Context (Pillar V)"
if [[ "${enqueued_n:-0}" -gt 0 ]]; then
  # Find the intent of the highest-priority enqueued task
  top_intent=""
  for f in "$QUEUE_DIR"/q-*.md; do
    [[ -f "$f" ]] || continue
    s="$(grep -E '^status:' "$f" 2>/dev/null | head -1 | sed 's/status:[[:space:]]*//' | tr -d '[:space:]')"
    if [[ "$s" == "enqueued" ]]; then
      top_intent="$(grep -E '^intent:' "$f" 2>/dev/null | head -1 | sed 's/intent:[[:space:]]*//')"
      break
    fi
  done

  if [[ -n "$top_intent" ]]; then
    printf 'Recall for top task: "%s"\n\n' "$top_intent"
    recall_out="$(_recall_context "$top_intent" 2>/dev/null || true)"
    if [[ -n "$recall_out" ]]; then
      printf '%s\n' "$recall_out"
    else
      printf '_(recall not available or no relevant history found)_\n'
    fi
  else
    printf '_(no enqueued tasks to recall context for)_\n'
  fi
else
  printf '_(no enqueued tasks — recall skipped)_\n'
fi

# ── Section: Frozen summary at end (if frozen, repeat action) ─────────────────
if [[ "$FROZEN" -eq 1 ]]; then
  _section "ACTION REQUIRED: System is FROZEN"
  printf 'Run: harness queue clear-freeze\n'
  printf 'Reason: %s\n' "$FREEZE_CONTENT"
fi

# ── Deliver notification ───────────────────────────────────────────────────────
BRIEF_SUMMARY="Morning brief ready"
if [[ "$FROZEN" -eq 1 ]]; then
  BRIEF_SUMMARY="[FROZEN] Morning brief — system halted, run clear-freeze"
elif [[ "$run_count" -gt 0 ]]; then
  BRIEF_SUMMARY="Morning brief: ${run_count} overnight run(s), ${staged_n:-0} staged"
elif [[ "${total_n:-0}" -gt 0 ]]; then
  BRIEF_SUMMARY="Morning brief: quiet night, ${total_n:-0} task(s) in queue"
else
  BRIEF_SUMMARY="Morning brief: quiet night — queue empty"
fi

if [[ "$NOTIFY_SKIP" != "1" ]] && [[ -x "$NOTIFY" ]]; then
  bash "$NOTIFY" "$BRIEF_SUMMARY" default 2>/dev/null || true
fi

printf '\n---\n_Brief written to: %s_\n' "$BRIEF_FILE"
