#!/usr/bin/env bash
# ABOUTME: Generates docs/spec-registry.yaml from YAML frontmatter in spec files.
# ABOUTME: Recursively scans the entire repo for .md files with frontmatter.
# ABOUTME: Extracts domain, skills, schemas and writes a consolidated registry.
# ABOUTME: Specs without frontmatter get stub entries and a stderr warning.
# ABOUTME: Run from the project root. Creates docs/ if needed. Auto-stages output.

set -euo pipefail

# Create docs/ if it doesn't exist
mkdir -p docs

OUTPUT="docs/spec-registry.yaml"

# Write header
cat > "$OUTPUT" << 'HEADER'
# Auto-generated from spec frontmatter. Do not edit manually.
# Regenerated by rebuild-spec-registry.sh when *.md files change.
HEADER

# Collect all .md files in the repo, excluding known non-spec patterns
spec_files=()
while IFS= read -r -d '' f; do
  basename_lower=$(basename "$f" | tr '[:upper:]' '[:lower:]')
  # Skip known non-spec files
  case "$basename_lower" in
    readme.md|changelog.md|contributing.md|license.md|code_of_conduct.md) continue ;;
    claude.md|memory.md|spec-registry.yaml) continue ;;
  esac
  spec_files+=("$f")
done < <(find . -name "*.md" -type f \
  -not -path "./.git/*" \
  -not -path "./.claude/*" \
  -not -path "./node_modules/*" \
  -not -path "./.venv*/*" \
  -not -path "./venv/*" \
  -not -path "./__pycache__/*" \
  -not -path "./.worktrees/*" \
  -not -path "*/node_modules/*" \
  -not -path "*/.claude/worktrees/*" \
  -print0 | sort -z)

if [ ${#spec_files[@]} -eq 0 ]; then
  echo "No .md files found in repo" >&2
  exit 0
fi

# Track domains we've already seen to handle duplicates
declare -A seen_domains

for filepath in "${spec_files[@]}"; do
  # Normalize path (strip leading ./)
  filepath="${filepath#./}"

  # Check if file starts with frontmatter delimiter
  first_line=$(head -1 "$filepath")
  if [ "$first_line" != "---" ]; then
    # No frontmatter: generate stub entry from filename
    basename_no_ext=$(basename "$filepath" .md)
    # Strip date prefix (YYYY-MM-DD-) if present
    domain=$(echo "$basename_no_ext" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//')
    # Strip common suffixes like -design, -implementation
    domain=$(echo "$domain" | sed -E 's/-(design|implementation)$//')
    # Lowercase and replace underscores with hyphens
    domain=$(echo "$domain" | tr '[:upper:]' '[:lower:]' | tr '_' '-')

    # Handle duplicate domains by appending parent dir
    if [ -n "${seen_domains[$domain]:-}" ]; then
      parent_dir=$(basename "$(dirname "$filepath")")
      domain="${parent_dir}-${domain}"
    fi
    # Still duplicate? Append full path hash
    if [ -n "${seen_domains[$domain]:-}" ]; then
      domain="${domain}-$(echo "$filepath" | md5 -q | head -c 6)"
    fi
    seen_domains[$domain]=1

    printf '\n%s:\n  spec: %s\n  skills: []\n  schemas: []\n' "$domain" "$filepath" >> "$OUTPUT"
    continue
  fi

  # Extract frontmatter: read lines between first and second ---
  domain=""
  skills=""
  schemas=""
  in_frontmatter=false
  while IFS= read -r line; do
    if [ "$line" = "---" ]; then
      if $in_frontmatter; then
        break
      else
        in_frontmatter=true
        continue
      fi
    fi
    if $in_frontmatter; then
      key=$(echo "$line" | sed -n 's/^\([a-zA-Z_]*\):.*/\1/p')
      value=$(echo "$line" | sed -n 's/^[a-zA-Z_]*: *//p')
      case "$key" in
        domain)  domain="$value" ;;
        skills)  skills="$value" ;;
        schemas) schemas="$value" ;;
      esac
    fi
  done < "$filepath"

  # If domain is empty after parsing, derive from filename
  if [ -z "$domain" ]; then
    basename_no_ext=$(basename "$filepath" .md)
    domain=$(echo "$basename_no_ext" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//')
    domain=$(echo "$domain" | sed -E 's/-(design|implementation)$//')
    domain=$(echo "$domain" | tr '[:upper:]' '[:lower:]' | tr '_' '-')
  fi

  # Default empty fields
  [ -z "$skills" ] && skills="[]"
  [ -z "$schemas" ] && schemas="[]"

  # Handle duplicate domains
  if [ -n "${seen_domains[$domain]:-}" ]; then
    parent_dir=$(basename "$(dirname "$filepath")")
    domain="${parent_dir}-${domain}"
  fi
  if [ -n "${seen_domains[$domain]:-}" ]; then
    domain="${domain}-$(echo "$filepath" | md5 -q | head -c 6)"
  fi
  seen_domains[$domain]=1

  printf '\n%s:\n  spec: %s\n  skills: %s\n  schemas: %s\n' "$domain" "$filepath" "$skills" "$schemas" >> "$OUTPUT"
done

# Stage if inside a git repo
if git rev-parse --is-inside-work-tree &>/dev/null; then
  git add "$OUTPUT"
fi
echo "Registry written to $OUTPUT with ${#spec_files[@]} entries."
