#!/bin/bash
# ABOUTME: Weekly self-audit script that reports ~/.claude system health.
# ABOUTME: Measures disk usage, debug log volume, project count, session stats.
# ABOUTME: Detects stale worktree data and oversized directories.
# ABOUTME: Writes a markdown report to ~/Code/pm_os/reports/claude-health/.
# ABOUTME: Always exits 0 to avoid blocking scheduled pipelines.

set -euo pipefail

# Audit failure should never block anything.
trap 'exit 0' ERR

CLAUDE_DIR="$HOME/.claude"
REPORT_DIR="$HOME/Code/pm_os/reports/claude-health"
REPORT_DATE=$(date +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/audit-${REPORT_DATE}.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Ensure output directory exists.
mkdir -p "$REPORT_DIR"

# disk_usage_human <path>
# Returns human-readable disk usage for a path. Falls back to "0B" if path missing.
disk_usage_human() {
  if [ -d "$1" ]; then
    du -sh "$1" 2>/dev/null | cut -f1
  else
    echo "0B"
  fi
}

# --- Gather metrics ---

# 1. Total disk usage.
TOTAL_SIZE=$(disk_usage_human "$CLAUDE_DIR")

# 2. Top 5 largest subdirectories.
TOP5_DIRS=$(du -sh "$CLAUDE_DIR"/*/ 2>/dev/null | sort -rh | head -5 | sed "s|$CLAUDE_DIR/|./|g" || echo "  (unable to measure)")

# 3. Debug log volume.
DEBUG_COUNT=0
DEBUG_SIZE="0B"
if [ -d "$CLAUDE_DIR/debug" ]; then
  DEBUG_COUNT=$(find "$CLAUDE_DIR/debug" -type f 2>/dev/null | wc -l | tr -d ' ')
  DEBUG_SIZE=$(disk_usage_human "$CLAUDE_DIR/debug")
fi

# 4. Project count.
PROJECT_COUNT=0
if [ -d "$CLAUDE_DIR/projects" ]; then
  PROJECT_COUNT=$(find "$CLAUDE_DIR/projects" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l | tr -d ' ')
fi

# 5. Sessions in last 7 days (files in debug/ with mtime < 7 days).
RECENT_SESSIONS=0
if [ -d "$CLAUDE_DIR/debug" ]; then
  RECENT_SESSIONS=$(find "$CLAUDE_DIR/debug" -type f -mtime -7 2>/dev/null | wc -l | tr -d ' ')
fi

# 6. Stale worktree data (project directories containing "worktree" in their path).
WORKTREE_DATA=""
if [ -d "$CLAUDE_DIR/projects" ]; then
  while IFS= read -r wt_dir; do
    [ -z "$wt_dir" ] && continue
    wt_size=$(disk_usage_human "$wt_dir")
    wt_name=$(echo "$wt_dir" | sed "s|$CLAUDE_DIR/projects/||")
    WORKTREE_DATA="${WORKTREE_DATA}- \`${wt_name}\` -- ${wt_size}
"
  done < <(find "$CLAUDE_DIR/projects" -mindepth 1 -maxdepth 1 -type d -name "*worktree*" 2>/dev/null)
fi
[ -z "$WORKTREE_DATA" ] && WORKTREE_DATA="None found."

# --- Write report ---

cat > "$REPORT_FILE" <<EOF
# Claude Health Audit -- ${REPORT_DATE}

Generated: ${TIMESTAMP}

## Disk Usage

**Total ~/.claude size:** ${TOTAL_SIZE}

### Top 5 Largest Subdirectories

\`\`\`
${TOP5_DIRS}
\`\`\`

## Debug Logs

- **File count:** ${DEBUG_COUNT}
- **Total size:** ${DEBUG_SIZE}

## Projects

- **Project memory directories:** ${PROJECT_COUNT}

## Session Activity (Last 7 Days)

- **Sessions:** ${RECENT_SESSIONS}

## Stale Worktree Data

${WORKTREE_DATA}

---
*Report generated by weekly-audit.sh*
EOF

echo "Audit report written to: $REPORT_FILE"

exit 0
